version: "3.1"

services:
  zpi-ams-service:
    build: ./ZPI-AMS-service
    ports:
      - "10000:10000"
    environment:
      - SPRING_MAIL_HOST=mail
      - SPRING_MAIL_USERNAME=admin@zpi.com
      - SPRING_MAIL_PASSWORD=admin
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
    links:
      - "mailserver:mail"
  db:
    image: postgres:14.1
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=analysis_db
  zpi-analysis-service:
    build: ./ZPI-analysis-service
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/analysis_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  zpi-authorize-service:
    build: ./ZPI-authorize-service
    links:
      - "zpi-ams-service:ams"
      - "zpi-analysis-service:analysis"
      - "mailserver:mail"
    environment:
      - SPRING_MAIL_HOST=mail
      - SPRING_MAIL_USERNAME=admin@zpi.com
      - SPRING_MAIL_PASSWORD=admin
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
      - AMS_URL=http://ams:10000
      - ANALYSIS_URL=http://analysis:5000
  zpi-demo-ui:
    build: ./ZPI-demo-UI
    environment:
      - PORT=3000
      - REACT_APP_AUTH_HOST=https://auth.zpi.fuf.me
      - REACT_APP_AUTH_CLIENT_ID=2
  nginx:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - "zpi-demo-ui:demo"
      - "zpi-ams-service:ams"
      - "zpi-authorize-service:auth"
      - "pgadmin:pgadmin"
      - "grafana:grafana"
  mailserver:
    image: docker.io/mailserver/docker-mailserver:10.3.0
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: zpi.com
    env_file: docker-mailserver/mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "35:25" # SMTP  (explicit TLS => STARTTLS)
      - "143:143" # IMAP4 (explicit TLS => STARTTLS)
      - "465:465" # ESMTP (implicit TLS)
      - "587:587" # ESMTP (explicit TLS => STARTTLS)
      - "993:993" # IMAP4 (implicit TLS)
    volumes:
      - mail-data:/var/mail/
      - mail-state:/var/mail-state/
      - mail-logs:/var/log/mail/
      - ./docker-mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
  pgadmin:
    image: dpage/pgadmin4:6.3
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@zpi.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=8888
  grafana:
    build: "./grafana"
    depends_on:
      - db

volumes:
  mail-data:
  mail-state:
  mail-logs:
  db-data:
