datasources:
  - name: PostgreSQL
    type: postgres
    isDefault: true
    typeName: PostgreSQL
    typeLogoUrl: public/app/plugins/datasource/postgres/img/postgresql_logo.svg
    access: proxy
    url: http://db:5432
    password: postgres
    user: postgres
    database: analysis_db
    basicAuth: false
    jsonData:
      postgresVersion: 903
      sslmode: "disable"
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: "file-path"
      tlsSkipVerify: true
    readOnly: false

