{
 "title": "Incidents and Requests",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Incident type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  t.type,\n  count(*)\nFROM incident_tuple_type as t\nGROUP BY t.type\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Requests and incidents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  count(id) AS \"requests\"\nFROM request_metadata\nWHERE\n  $__timeFilter(datetime)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  count(request_metadata.id) AS \"incidents\"\nFROM request_metadata, incident\nWHERE\n  $__timeFilter(datetime) and request_metadata.id = incident.request_id\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Request locations",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  country_name\nFROM\n  ip_info\n"
    }
   ]
  },
  {
   "title": "Incident severity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  -- $__timeGroupAlias(datetime,$__interval),\n  incident.severity,\n  count(*)\nFROM request_metadata, incident\nWHERE\n  request_metadata.id = incident.request_id\nGROUP BY incident.severity\nORDER BY 1"
    }
   ]
  }
 ]
}